# In this file you tell Other Apps which addons to include during the program execution.
# Addons are simply javascript files that are included while the app is running

# Index:      Addons to be executed when you are in /
# Editor:     Addons to be executed when you are in /edit
# Play:       Addons to be executed when you are in /play
# Embed:      Addons to be executed when you are in /embed
# Datainfo:   Addons to be executed when you are in /database/info

# extraToolbar.js      Extra toolbar in your app
# extraInsert.js       More items to add in the Insert list
# extraEditor.js       More options for your code editor
# extraEdits.js        More options for your app items
# keyboard.js          Add keyboard shortcuts in your editor
# dblclick.js          Open code editor when you double click an item
# unsave.js            Show "unsaved changes" dialog when you close the editor
# scaleApp.js          Apps are scaled to fit screen size
# dbAppGen.js          A replacement for the default database application generator

Index: []

Editor:
  - /static/addons/extraToolbar.js
  - /static/addons/extraInsert.js
  - /static/addons/extraEditor.js
  - /static/addons/extraEdits.js
  - /static/addons/keyboard.js
  - /static/addons/dblclick.js
  - /static/addons/unsave.js

Play:
  - /static/addons/scaleApp.js

Embed: []

Datainfo:
  - /static/addons/dbAppGen.js